{
 "title": "mini-api Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"mini-api-svc\", status=\"4xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency p99 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{job=\"mini-api-svc\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"mini-api-svc\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}